language: ruby
rvm:
- 2.6.2
notifications:
  slack:
    secure: HG2XkTHJHBsUi6G638FKGKcxWxvprHYvzHpcQrD5nYTEQTncENN+pbsOd3tU3c7wsff3dr1jTzzbmeC+VNmlOgPVLNbAdv7gqLW3+oG3L2LXr5BrKodmBGBIyMkyb79exC686H8swnmRaYq/yIyQYFUjEmgHnIqsPK0kJTa0vUoSEatVZVdFGiQHBQ3dcJH+/yPgYGHlXqtTbMYNDuzwlfx+MnWUQ7HTwsXyQ9YDs/xnwgmtkuWf+jIVPjk0d6rJB6m4m0tG6H99uptQHEf4myBGP2K6s3zlRTE5YoVDFdlV/pzFTR1/9UmGtjW8LLTeY+3cen2e6oyJKL6O4TGrqmQGqM/Nisc3092c30Qr0XP8YHTrAoDtbYp6IORhHXJGOVKAxoJh5CNSG1HtIXKeo3b5uhmdtqfvA1ilyfZv0LixowSTQ/VOo4V+VIDgkC6BESRWbbQ2hAbn5F4fWqhVtnAu9aOi0LuVr5DRW3KPCYJAg/5PU6E187gCW1GNhcRKKM8fVgIwIRuGHYcrzMl8llt9H1EBUjPC78Pi7W4j6bxb18J7Libf32LsYU4mmmRqsp9e4bKlqs01jc912eEyr7vK2lR118zSMvzOxDY/5PuuNV/R8nl1D7ONJkav/KeCMkvigaDfniEgdjxfDG4G7wA9VvC0lykepeY+HWfEqhc=
